version: '3.8'

name: url-shorter

volumes:
  url_shorter_data:

services:
  url_shorter_db:
    container_name: url_shorter_db
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    volumes:
      - url_shorter_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "UrlShorterDB"]
      interval: 30s
      timeout: 30s
      retries: 5

  url_shorter_app:
    container_name: url_shorter_app
    image: url-shorter_app:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - url_shorter_db